import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { AppWrapper } from '@form/shared';

const poppins = Poppins({
  weight: ['400', '300', '700', '500', '600'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <script
          async
          defer
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.GOOGLE_MAPS_KEY}&libraries=places`}
        ></script>

        <AppWrapper>{children}</AppWrapper>
      </body>
    </html>
  );
}
