import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { AppWrapper } from '@finsweet/shared';

const inter = Poppins({
  weight: ['500', '600', '400'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Pr2 Ekrative',
  description: 'Generated by create next app and Ivan Nesterenko',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppWrapper>{children}</AppWrapper>
      </body>
    </html>
  );
}
